/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface VCarousel {
        /**
          * The number of elements to show per page view. Defaults to 3
          * @type {number}
         */
        "pagesize": number;
        /**
          * Section title to use in heading
          * @type {string}
         */
        "sectionTitle": "Carousel!";
        /**
          * If defined/true, sets a mutation observer to reinitialize the component when child nodes are changed.  Otherwise ignores changes to child nodes.
          * @type {boolean}
         */
        "watchchildren": boolean;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLVCarouselElement extends Components.VCarousel, HTMLStencilElement {
    }
    var HTMLVCarouselElement: {
        prototype: HTMLVCarouselElement;
        new (): HTMLVCarouselElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "v-carousel": HTMLVCarouselElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface VCarousel {
        /**
          * The number of elements to show per page view. Defaults to 3
          * @type {number}
         */
        "pagesize"?: number;
        /**
          * Section title to use in heading
          * @type {string}
         */
        "sectionTitle"?: "Carousel!";
        /**
          * If defined/true, sets a mutation observer to reinitialize the component when child nodes are changed.  Otherwise ignores changes to child nodes.
          * @type {boolean}
         */
        "watchchildren"?: boolean;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "v-carousel": VCarousel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "v-carousel": LocalJSX.VCarousel & JSXBase.HTMLAttributes<HTMLVCarouselElement>;
        }
    }
}
